#- name: Install qemu-guest-agent package
#  hosts: all
#  become: true
#  become_method: ansible.builtin.sudo

#  tasks:
#    - name: Install qemu-guest-agent
#      ansible.builtin.apt:
#        name: qemu-guest-agent
#        state: present
---
- hosts: all
  gather_facts: false
  become: yes

  tasks:
    - name: update apt cache
      command: apt update

    - name: install qemu guest agent
      apt:
        name: qemu-guest-agent
        state: present

    - name: upgrade all packages
      command: apt upgrade -y

    - name: reboot host
      reboot:
