---
- name: Update, Upgrade, Autoremove, and Autoclean
  hosts: all
  become: true
  tasks:

     - name: Add Webmin repositories
       apt_repository: >
        repo='{{ item }}'
        state=present
       with_items:
         - 'deb http://download.webmin.com/download/repository sarge contrib'
         - 'deb http://webmin.mirror.somersettechsolutions.co.uk/repository sarge contrib'

     - name: Add Webmin key
       apt_key: >
        url='http://www.webmin.com/jcameron-key.asc'
        state=present
     - name: Install Webmin and prerequisites
       apt: >
        update_cache=yes
        pkg={{ item }}
        state=installed
       with_items:
         - perl
         - libnet-ssleay-perl
         - openssl
         - libauthen-pam-perl
         - libpam-runtime
         - libio-pty-perl
         - apt-show-versions
         - python
         - webmin
