---
- name: Install Webin on Ubuntu / Debian
  hosts: all
  become: yes
    tasks:
    - name: Install prerequisite
      apt:
        name:
        - perl
        - libnet-ssleay-perl
        - openssl
        - libauthen-pam-perl
        - libpam-runtime
        - libio-pty-perl
        - apt-show-versions
        - python
        - libwww-perl
        - liblwp-protocol-https-perl
        state: latest
        update_cache: yes

#    - name: Add key Webmin repository
#      apt_key:
#        url: https://www.webmin.com/jcameron-key.asc
#        state: present

    - name: Add Webmin repository
      apt_repository:
        repo: 'deb https://download.webmin.com/download/repository sarge contrib'
        state: present
        filename: webmin
        update_cache: yes

    - name: Install webmin
      apt:
        name:
        - webmin
        state: latest
