---
- name: Update, Upgrade, Autoremove, and Autoclean
  hosts: all
  become: true

  tasks:
  - name: Update package index
    apt:
      update_cache: yes

  - name: Upgrade packages
    apt:
      upgrade: yes

  - name: Autoremove packages
    apt:
      autoremove: yes

  - name: Autoclean packages
    apt:
      autoclean: yes