---
- name: Update, Upgrade, Autoremove, and Autoclean
  hosts: all
  become: true

  tasks:
  - name: Update package index
    apt:
      update_cache: yes

  - name: Upgrade packages
    apt:
      upgrade: yes

  - name: Autoremove packages
    apt:
      autoremove: yes
      purge: true

  - name: Autoclean packages
    apt:
      autoclean: yes

  - name: Update all packages to their latest version
    ansible.builtin.apt:
      name: "*"
      state: latest

  - name: Run the equivalent of "apt-get clean" as a separate step
    ansible.builtin.apt:
      clean: yes